name: Node CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-node@v6
      with:
        node-version: 24
    - name: yarn install
      run: yarn install
    - name: build
      run: yarn build
      env:
        CI: true
    - name: lint
      run: yarn lint
      env:
        CI: true
